void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
void main () { print ("Desktop app ready\n"); }
