ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
ready :- write('Rules loaded').
