FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
FROM ubuntu:latest
RUN echo 'Docker ready'
