BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
BEGIN { print "Parser ready" }
